# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MDB Social' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'

  pod 'NotificationBannerSwift', '~> 3.0.0'
  # Pods for MDB Social

end
